version: '3.8'

services:
  snake-game:
    image: nginx:alpine
    container_name: snake-game
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
